Ort 19
AbziBzi/ORT pull request #3
Opened 2021-02-02 09:47 UTC by AbziBzi

Finished ORT-19 task

2021-02-06 21:55 UTC, mantasmak requested changes

2021-02-06 21:55 UTC, mantasmak commented on backend/Orienteering/Orienteering.Domain/Entities/Game.cs
> +        }
Constructor is not necessary

2021-02-06 21:55 UTC, mantasmak commented on backend/Orienteering/Orienteering.Domain/Entities/Game.cs
> +        public DateTime UpdateDate { get; set; }
Inconsistent naming. Some properties have **DateTime** in their name, some have just **Date**. I suggest using **Date** instead of **DateTime** in the property name,

2021-02-06 21:55 UTC, mantasmak commented on backend/Orienteering/Orienteering.Domain/Entities/Game.cs
> +        public virtual ICollection<User> Participants { get; private set; }
**set** accessor should be **public**

2021-02-06 21:55 UTC, mantasmak commented on backend/Orienteering/Orienteering.Domain/Entities/Track.cs
> +        }
Constructor is not necessary

2021-02-06 21:55 UTC, mantasmak commented on backend/Orienteering/Orienteering.Domain/Entities/Track.cs
> +        public DateTime UpdateDate { get; set; }
Inconsistent naming, One property uses **Time** suffix and the other **Date**. I suggest changing **Time** to **Date**.

2021-02-06 21:55 UTC, mantasmak commented on backend/Orienteering/Orienteering.Domain/Entities/Track.cs
> +        public virtual ICollection<TrackPoint> TrackPoints { get; private set; }
Would it make sense to change property name **GamesWhereUsed** to just **Games**? Also the **set** accessor should be public.

2021-02-06 21:55 UTC, mantasmak commented on backend/Orienteering/Orienteering.Domain/Entities/User.cs
> +        }
Constructor is not necessary

2021-02-06 21:55 UTC, mantasmak commented on backend/Orienteering/Orienteering.Domain/Entities/User.cs
> +        public virtual ICollection<Track> CreatedTracks { get; private set; }
Would it make sense to change property name **ParticipatingGames** to **ParticipatingIn**? Also the set accessor should be public.

2021-02-19 11:28 UTC, AbziBzi commented on backend/Orienteering/Orienteering.Domain/Entities/Track.cs
> +        public virtual ICollection<TrackPoint> TrackPoints { get; private set; }
I have to disagree with changing property name **GamesWhereUsed** to just **Game**. Name **Game** can be misunderstanding while reading  class **Track**. Someone might think that **Track** has its own games, while the **Track** is part of the **Game**.

2021-02-19 11:33 UTC, AbziBzi commented on backend/Orienteering/Orienteering.Domain/Entities/User.cs
> +        public virtual ICollection<Track> CreatedTracks { get; private set; }
Name **ParticipatingIn** might be confusing. Someone who cannot see that this is a **Game** collection would need to check what **ParticipatingIn** property is.

2021-02-19 11:42 UTC, AbziBzi commented on backend/Orienteering/Orienteering.Domain/Entities/User.cs
> +        public virtual ICollection<Track> CreatedTracks { get; private set; }
After much thought I can agree that name **ParticipatingGames** is not entirely appropriate as it refers to present tense, while the  **Game** in the collection may already end.

2021-02-19 16:31 UTC, mantasmak commented on backend/Orienteering/Orienteering.Domain/Entities/User.cs
> +        public virtual ICollection<Track> CreatedTracks { get; private set; }
The main issue I see is that when **User** has a property called **ParticipatingGames** it sounds like **Games** are participating in **User** and not the other way around. Is it just me?

2021-02-26 18:34 UTC, mantasmak approved these changes

2021-02-26 18:34 UTC, merged